name: StockCheckBot

on:
  schedule:
    # 日本時間 15:08 (世界標準時 06:08)
    # 末尾の '1-5' が「月曜(1)から金曜(5)」という意味です
    - cron: '8 6 * * 1-5'
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install yfinance requests pandas
      - name: Run scripts
        env:
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: |
          python main.py
          python moomoo.py
          python volume.py
