name: StockCheckBot

on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install pandas==2.0.3 yfinance requests
          pip install git+https://github.com/twopirllc/pandas-ta.git@main
      - name: Run script
        run: python main.py
        env:
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
